ALTER TABLE user_review_log
  ADD COLUMN IF NOT EXISTS review_score DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS review_max_score DOUBLE PRECISION;

ALTER TABLE IF EXISTS user_kanji_review_log
  ADD COLUMN IF NOT EXISTS review_score DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS review_max_score DOUBLE PRECISION;
